### ISSUE TITLE
Scrap Images For Comics

### ISSUE THREAD

**Issue by hollowprojects** [fdac19/ComicScrapper#1]
https://readcomicsonline.ru/

Scrap one series from the site

**Comment by ghost** [comment]
Opened PR #5 that will accept a URL/Series to scrape, and it will grab all chapters/images associated with the entered URL

**Comment by hollowprojects** [comment]
Casey is a great job on this. Please note that this will save in your docker and not your local machine. This could though be all used in a juptier notebook now
